# Generated by Django 5.2 on 2026-06-07 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_employee_name_alter_employee_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorder',
            name='address_details',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='governorate',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
