# Generated by Django 5.2 on 2026-07-08 12:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_salesorder_address_details_salesorder_governorate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='receipt',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
