# Generated by Django 5.2 on 2026-04-27 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='attribute_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='dashboard.attributevalue'),
        ),
    ]
