# Generated by Django 5.2 on 2026-05-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_adminpushdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
