# Generated by Django 5.2 on 2026-06-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_shippingrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_district',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
