# Generated by Django 5.2 on 2026-04-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinestore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestorder',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
